UPDATE cars SET image_url = 'https://febrrgqpyqqrewcohomx.supabase.co/storage/v1/object/public/cars/image0.jpeg' WHERE name = 'Duster';
UPDATE cars SET image_url = 'https://febrrgqpyqqrewcohomx.supabase.co/storage/v1/object/public/cars/image1.jpeg' WHERE name = 'Fiat 500';
UPDATE cars SET image_url = 'https://febrrgqpyqqrewcohomx.supabase.co/storage/v1/object/public/cars/image2.jpeg' WHERE name = 'Duster (2)';
UPDATE cars SET image_url = 'https://febrrgqpyqqrewcohomx.supabase.co/storage/v1/object/public/cars/image3.jpeg' WHERE name = 'Clio 4';
UPDATE cars SET image_url = 'https://febrrgqpyqqrewcohomx.supabase.co/storage/v1/object/public/cars/image4.jpeg' WHERE name = 'Creta';
UPDATE cars SET image_url = 'https://febrrgqpyqqrewcohomx.supabase.co/storage/v1/object/public/cars/image5.jpeg' WHERE name = 'Clio 4 (2)';
UPDATE cars SET image_url = 'https://febrrgqpyqqrewcohomx.supabase.co/storage/v1/object/public/cars/image6.jpeg' WHERE name = 'Sandero';
UPDATE cars SET image_url = 'https://febrrgqpyqqrewcohomx.supabase.co/storage/v1/object/public/cars/image7.jpeg' WHERE name = 'i10';
UPDATE cars SET image_url = 'https://febrrgqpyqqrewcohomx.supabase.co/storage/v1/object/public/cars/image8.jpeg' WHERE name = 'Jumpy 9 Places';
UPDATE cars SET image_url = 'https://febrrgqpyqqrewcohomx.supabase.co/storage/v1/object/public/cars/image9.jpeg' WHERE name = 'Fiat 500 XL';
UPDATE cars SET image_url = 'https://febrrgqpyqqrewcohomx.supabase.co/storage/v1/object/public/cars/image10.jpeg' WHERE name = 'Jogger';
UPDATE cars SET image_url = 'https://febrrgqpyqqrewcohomx.supabase.co/storage/v1/object/public/cars/image11.jpeg' WHERE name = 'Clio 5 Essence';
UPDATE cars SET image_url = 'https://febrrgqpyqqrewcohomx.supabase.co/storage/v1/object/public/cars/image12.jpeg' WHERE name = 'Clio 5 Alpine';
UPDATE cars SET image_url = 'https://febrrgqpyqqrewcohomx.supabase.co/storage/v1/object/public/cars/image13.jpeg' WHERE name = 'Berlingo';